### ISSUE TITLE
websocket client can't connect to the server on window 

### ISSUE THREAD

**Issue by schyjxy** [Jamol/kuma#30] opened 2021-11-27 02:15 UTC
log:
INFO [19904] IocpSocket_6:: connect, host=192.168.124.6, port=8183
INFO [19904] IocpPoll::registerFd, fd=748, events=7
INFO [19904] IocpSocket_6:: connect_i, fd=748, local_ip=0.0.0.0, local_port=12431, state=2
INFO [6760] DNS resolving thread exited
INFO [21288] IocpSocket_6:: onConnect, err=0, state=2
INFO [21288] TcpSocket_5:: onConnect, err=0
INFO [21288] H1xStream_4:: onHttpEvent, ev=0
WARN [21288] IocpSocket_6:: onReceive, io_size=0, state=3, pending=0
INFO [21288] IocpSocket_6:: onClose, err=-12, state=3

**Comment by Jamol** [comment] 2021-11-27 15:25
io_size=0 on receive means the connection was closed by peer. could you post the logs of both endpoints? or pls describe the dup steps?

**Comment by Jamol** [comment] 2021-11-30 04:45
Thanks for the info, I will try to reproduce with ws

**Comment by Jamol** [comment] 2021-11-30 06:39
I had reproduced the issue, the root cause is the url "?token=android" is not valid to ws, should be "/?token=android".

**Comment by schyjxy** [comment] 2021-11-30 11:43
But the url it's valid in javascript. And the issue will not happen in Linux or previous  version.

**Comment by Jamol** [comment] 2021-12-01 03:27
The url "ws://192.168.3.111:8080?token=android" will be converted to "ws://192.168.3.111:8080/?token=android" if you access it from Browser. I recommend adding the url path.

**Comment by Jamol** [comment] 2021-12-04 08:28
closed

**Closed by Jamol** 2021-12-04 08:28 UTC
